"""Generated workflow registry for the Hermes `/adw` command.

Run `python3 tools/build_skills.py`; do not edit this file directly.
"""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class WorkflowDefinition:
    token: str
    skill: str
    skill_dir: str
    description: str
    preset: str = ""


@dataclass(frozen=True)
class Route:
    workflow: str
    skill: str
    payload: str
    preset: str = ""


WORKFLOW_DEFINITIONS: tuple[WorkflowDefinition, ...] = (
    WorkflowDefinition('analyze-production', 'adw-analyze-production', 'adw-analyze-production', 'Triages production feedback, logs, metrics, and incidents into continue, fix-forward, or rollback recommendations. Use when a deployment misbehaves, users report a live defect, or runtime evidence needs structured analysis.', ''),
    WorkflowDefinition('audit-dependencies', 'adw-audit-dependencies', 'adw-audit-dependencies', 'Audits dependency, build-tool, and toolchain changes for security, maintenance, compatibility, and release risk. Use for upgrade PRs, lockfile changes, supply-chain review, or dependency health checks.', ''),
    WorkflowDefinition('chain', 'adw-chain', 'adw-chain', 'Coordinates a bounded multi-stage ADW delivery sequence while preserving every quality and approval gate. Use when the user requests plan-through-merge, full rollout, or another explicit chain of delivery stages.', ''),
    WorkflowDefinition('create-adr', 'adw-create-adr', 'adw-create-adr', 'Creates a reviewable Architecture Decision Record with context, options, decision, and consequences. Use for architectural, security-boundary, platform, or long-lived delivery decisions that need durable rationale.', ''),
    WorkflowDefinition('do-impl', 'adw-do-impl', 'adw-do-impl', 'Implements an approved plan, runs manifest-declared minimal verification, and prepares a reviewable commit or pull request. Use when coding a planned ADW change directly in a repository with an ADW task manifest.', ''),
    WorkflowDefinition('do-impl-delegate', 'adw-do-impl-delegate', 'adw-do-impl-delegate', 'Delegates an approved implementation through a backend-neutral brief and independently verifies the returned change. Use when another agent or worker should implement an ADW plan while the orchestrator retains delivery gates.', ''),
    WorkflowDefinition('merge-feature', 'adw-merge-feature', 'adw-merge-feature', 'Merges a validated pull request into an explicitly approved destination and deploys only when separately requested and gated. Use after review evidence is complete or when the user asks to merge or deliver an approved PR.', ''),
    WorkflowDefinition('plan-feature', 'adw-plan', 'adw-plan', 'Plans a feature or bugfix as a reviewable delivery unit with branch, issue, acceptance criteria, verification, and rollback notes. Use when scoping a new capability, investigating a defect, or preparing non-trivial ADW work.', 'type=feature'),
    WorkflowDefinition('plan-bugfix', 'adw-plan', 'adw-plan', 'Plans a feature or bugfix as a reviewable delivery unit with branch, issue, acceptance criteria, verification, and rollback notes. Use when scoping a new capability, investigating a defect, or preparing non-trivial ADW work.', 'type=bugfix'),
    WorkflowDefinition('rollback-deployment', 'adw-rollback-deployment', 'adw-rollback-deployment', 'Restores a failed deployment with the repository-declared rollback strategy and verifies the restored identity and health. Use for incident recovery or when an approved release must be rolled back safely.', ''),
    WorkflowDefinition('self-improve', 'adw-self-improve', 'adw-self-improve', 'Persists an explicitly requested workflow improvement in the correct ADW, context, or project layer through a reviewable pull request. Use when the user asks the delivery system to learn, improve, or codify a recurring lesson.', ''),
    WorkflowDefinition('test-feature', 'adw-test-feature', 'adw-test-feature', 'Reviews and validates a pull request with local quality, preview deployment, smoke checks, and optional E2E evidence. Use before merge or when asked to test a feature branch, PR, or preview environment.', ''),
    WorkflowDefinition('validate-regression', 'adw-validate-regression', 'adw-validate-regression', 'Runs targeted or broad regression checks against a pull request, branch, deployment, or release candidate and records honest evidence. Use for risk-based validation, regression investigation, or pre-release confidence.', ''),
)

WORKFLOWS: dict[str, str] = {definition.token: definition.skill for definition in WORKFLOW_DEFINITIONS}
_DEFINITION_BY_WORKFLOW = {definition.token: definition for definition in WORKFLOW_DEFINITIONS}
_SKILL_DIR_BY_NAME: dict[str, str] = {"adw-core": "adw-core"} | {
    definition.skill: definition.skill_dir for definition in WORKFLOW_DEFINITIONS
}


def normalize_token(token: str) -> str:
    return (token or "").strip().lower().replace("_", "-")


def canonical_workflow(token: str) -> str | None:
    workflow = normalize_token(token)
    return workflow if workflow in WORKFLOWS else None


def parse_route(raw_args: str) -> Route | None:
    args = (raw_args or "").strip()
    if not args:
        return None
    workflow_token, _, payload = args.partition(" ")
    workflow = canonical_workflow(workflow_token)
    if workflow is None:
        return None
    definition = _DEFINITION_BY_WORKFLOW[workflow]
    return Route(workflow=workflow, skill=definition.skill, payload=payload.strip(), preset=definition.preset)


def skill_dir_for_name(skill_name: str) -> str:
    return _SKILL_DIR_BY_NAME[skill_name]


def workflow_description(workflow: str) -> str:
    return _DEFINITION_BY_WORKFLOW[workflow].description
